include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    todo: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_function_literals_in_foreach_calls: false
    constant_identifier_names: false
    void_checks: false
    must_be_immutable: false
    use_key_in_widget_constructors: false
