include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    todo: false
    avoid_function_literals_in_foreach_calls: false
    constant_identifier_names: false
    void_checks: false
    must_be_immutable: false
    use_key_in_widget_constructors: false

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
